apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-operator
spec:
  replicas: 1
  serviceAccountName: marketplace-operator-serviceaccount
  selector:
    matchLabels:
      name: marketplace-operator
  template:
    metadata:
      labels:
        name: marketplace-operator
    spec:
      containers:
        - name: marketplace-operator
          image: quay.io/redhat/marketplace
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - marketplace-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "marketplace-operator"
