kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: marketplace-operator
rules:
- apiGroups:
  - marketplace.redhat.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-marketplace-operator
subjects:
- kind: ServiceAccount
  name: marketplace-operator-serviceaccount
  namespace: marketplace
roleRef:
  kind: ClusterRole
  name: marketplace-operator
  apiGroup: rbac.authorization.k8s.io
